# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_objective_c <- function(Z, X, alpha_matrix, nonzero_index, Sigma_c) {
    .Call('_McDisCoV_fast_objective_c', PACKAGE = 'McDisCoV', Z, X, alpha_matrix, nonzero_index, Sigma_c)
}

fast_half1_half2 <- function(PhiiXi_list, PhiiZi_list, Sigma_list) {
    .Call('_McDisCoV_fast_half1_half2', PACKAGE = 'McDisCoV', PhiiXi_list, PhiiZi_list, Sigma_list)
}

fast_H_theta_theta <- function(PhiiXi_list, Sigma_list) {
    .Call('_McDisCoV_fast_H_theta_theta', PACKAGE = 'McDisCoV', PhiiXi_list, Sigma_list)
}

fast_theta_gradient <- function(PhiiXi_list, PhiiZi_list, Sigma_list, theta_hat) {
    .Call('_McDisCoV_fast_theta_gradient', PACKAGE = 'McDisCoV', PhiiXi_list, PhiiZi_list, Sigma_list, theta_hat)
}

