# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_H_theta_theta <- function(PhiiXi_list, Sigma_list) {
    .Call(`_McDisCoV_fast_H_theta_theta`, PhiiXi_list, Sigma_list)
}

fast_half1_half2 <- function(PhiiXi_list, PhiiZi_list, Sigma_list) {
    .Call(`_McDisCoV_fast_half1_half2`, PhiiXi_list, PhiiZi_list, Sigma_list)
}

